name: Test Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.18.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: go test ./... -v -run Unit

  upload:
    name: Upload Workflow Event Payload
    runs-on: ubuntu-latest
    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: event-payload
          path: ${{ github.event_path }}
